# Generated by Django 5.2.1 on 2025-05-17 09:26

import django.db.models.deletion
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "raw_content",
                    markdownx.models.MarkdownxField(verbose_name="Markdown原始内容"),
                ),
                (
                    "rendered_content",
                    models.TextField(editable=False, verbose_name="渲染后的html"),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("pub_date", models.DateField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_date",
                    models.DateField(auto_now_add=True, verbose_name="comment date"),
                ),
                ("comment_context", models.CharField(max_length=500)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyBlog.article",
                        verbose_name="关联文章",
                    ),
                ),
            ],
        ),
    ]
