# Generated by Django 5.2.1 on 2025-05-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyBlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
        ),
    ]
