# Generated by Django 5.2.1 on 2025-05-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyBlog", "0002_alter_article_pub_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("slug", models.SlugField(default="about-page", unique=True)),
            ],
        ),
    ]
