# Generated by Django 5.2.1 on 2025-06-04 11:02

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("MyBlog", "0003_about"),
    ]

    operations = []
