# Generated by Django 5.2.1 on 2025-06-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyBlog", "0004_auto_20250604_1902"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "文章标签",
                "verbose_name_plural": "文章标签",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "文章分类",
                "verbose_name_plural": "文章分类",
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
            },
        ),
        migrations.RemoveField(
            model_name="comment",
            name="comment_context",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="comment_date",
        ),
        migrations.AddField(
            model_name="about",
            name="title",
            field=models.CharField(default="关于我们", max_length=200),
        ),
        migrations.AddField(
            model_name="article",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="最后更新"),
        ),
        migrations.AddField(
            model_name="article",
            name="overview",
            field=models.TextField(
                blank=True, default="", max_length=300, verbose_name="概述"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="visited_num",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="访问量"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="word_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="字数"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.CharField(default="匿名用户", max_length=100),
        ),
        migrations.AddField(
            model_name="comment",
            name="body",
            field=models.CharField(default="", max_length=500, verbose_name="评论内容"),
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="评论时间"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="content",
            field=models.TextField(verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="MyBlog.article",
                verbose_name="关联文章",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MyBlog.articletag",
                verbose_name="标签",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MyBlog.category",
                verbose_name="分类",
            ),
        ),
    ]
