# Generated by Django 5.2.1 on 2025-06-04 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MyBlog", "0005_articletag_category_alter_article_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-comment_date"],
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
            },
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_at",
            new_name="comment_date",
        ),
    ]
