# Generated by Django 5.2.1 on 2025-06-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyBlog", "0006_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="tags",
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="MyBlog.articletag", verbose_name="标签"
            ),
        ),
    ]
