# Generated by Django 5.2.1 on 2025-06-06 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyBlog", "0007_remove_article_tags_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article",
                to="MyBlog.category",
                verbose_name="分类",
            ),
        ),
    ]
