# Generated by Django 5.2.1 on 2025-06-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyBlog", "0008_alter_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="邮箱(不会公开)"
            ),
        ),
    ]
