# Generated by Django 5.2.1 on 2025-06-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyBlog", "0009_comment_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(default="匿名用户", max_length=100, verbose_name="用户"),
        ),
    ]
