# Generated by Django 5.2.1 on 2025-06-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyBlog", "0010_alter_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_img",
            field=models.ImageField(
                blank=True, null=True, upload_to="article_cover/", verbose_name="文章封面"
            ),
        ),
    ]
