# Generated by Django 5.2.1 on 2025-06-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyBlog", "0011_article_cover_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="日期")),
                ("total_visits", models.IntegerField(default=0, verbose_name="总访问量")),
                (
                    "unique_visitors",
                    models.IntegerField(default=0, verbose_name="唯一访客数"),
                ),
                ("unique_ips", models.IntegerField(default=0, verbose_name="唯一IP数")),
            ],
            options={
                "verbose_name": "访问统计摘要",
                "verbose_name_plural": "访问统计摘要",
            },
        ),
        migrations.CreateModel(
            name="VisitRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="用户代理"
                    ),
                ),
                (
                    "visited_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="访问时间"),
                ),
                ("visited_path", models.CharField(max_length=200, verbose_name="访问路径")),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="会话ID"
                    ),
                ),
                (
                    "is_unique_today",
                    models.BooleanField(default=False, verbose_name="今日唯一时间"),
                ),
            ],
            options={
                "verbose_name": "访问记录",
                "verbose_name_plural": "访问记录",
                "indexes": [
                    models.Index(
                        fields=["ip_address", "visited_time"],
                        name="MyBlog_visi_ip_addr_1f360e_idx",
                    ),
                    models.Index(
                        fields=["session_id", "visited_time"],
                        name="MyBlog_visi_session_de9193_idx",
                    ),
                    models.Index(
                        fields=["visited_time"], name="MyBlog_visi_visited_3fc898_idx"
                    ),
                ],
            },
        ),
    ]
